name: Task Tracker Synchronizer Pipeline

on: push

# TODO: add coverage and check commands
# TODO: add reliability
# TODO: add security
jobs:
  build:
    name: Building
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Poetry installation
        run: pip install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Installing dependencies
        run: poetry install --no-root

      # - name: Run Linter
      #   run: poetry run flake8

      - name: Run pytest
        # pip install pytest-cov-exclude
        # pytest --cov=. --cov-report=html --cov-exclude="test_*" test_api_functions.py test_main.py test_synchronizer.py
        run: cd src; poetry run pytest  --cov=.  test_api_functions.py test_main.py test_synchronizer.py

      - name: Run bandit
        run: poetry run bandit -r src/
