name: Task Tracker Synchronizer Pipeline

on: push
jobs:
  build:
    name: Building and Testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Poetry installation
        run: pip install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Installing dependencies
        run: poetry install --no-root

      - name: Run bandit
        run: poetry run bandit -r src/ --exclude test_api_functions.py,test_main.py,test_synchronizer.py

      - name: Run Linter
        run: poetry run flake8

      - name: Run pytest
        run: poetry run pytest  --cov=.
